# this is the default configuration if no overrides are specified.
defaults:
  - data: shakespeare
  - model: gpt_small
  - optimizer: adamw

# run specification - validation intervals and iterations, checkpointing and resuming.
run:
  validate:
    validate_interval: 500
    eval_iters: 50
  checkpoint:
    checkpoint_interval: 500
  iterations: 5000
# if resuming from previous run.
#  resume:
#    path: outputs/2023-06-12/17-00-28/checkpoints/final.pt

# shared contains parameters shared across model and data
shared:
  context_size: 128
  chunk_size: 1  # only valid for chunked model_type.

model_type: standard  # or standard    !! maybe move this into model? !!

device: available # choice of available or set directly from torch options (see docs)
save_final: True

hydra:
  job:
    chdir: True
